server:
  port: 8080

spring:
  profiles:
    active: production

---
spring:
  profiles: production
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url:
    username:
    password: