server:
  port: 8080

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/jachwirus
    username: root
    password: hello

---
spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  profiles: production
